apiVersion: apps/v1
kind: Deployment
metadata:
  name: hc-vault-log-test
  namespace: hc-vault
  labels:
    app: hc-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hc-vault
  template:
    metadata:
      labels:
        app: hc-vault
    spec:
      containers:
      - name: hc-vault-test-logs
        image: ercandevops/hc-vault-test-logs
