apiVersion: v1
kind: Pod
metadata:
  name: test-hc-vault-logs
  namespace: hc-vault
  labels:
    app: hc-vault
spec:
  containers:
  - name: hc-vault-test-logs-sealed
    image: ercandevops/hc-vault-test-logs:win
    imagePullPolicy: Always